---
- hosts: jenkins-controller
  become: true
  vars:
    java_packages:
      - java-17-amazon-corretto-devel
    jenkins_packages:
      - jenkins  
  tasks:
    - name: Update local package index
      yum:
        name: '*'
        state: latest 
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins-CI key
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest 
    - name: Install Java
      yum:
        name: "{{ java_packages }}"
        state: present
    - name: Install Jenkins
      yum:
        name: "{{ jenkins_packages }}"
        state: present
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
    - name: Enable service jenkins
      service:
        name: jenkins
        enabled: yes
