--- 
- hosts: maven
  become: true
  vars:
    java_packages:
      - java-17-amazon-corretto-devel
  tasks: 
    - name: Update YUM package cache
      yum:
        update_cache: yes
    - name: Upgrade packages
      yum:
        name: '*'
        state: latest 
    - name: Install Java
      yum:
        name: "{{ java_packages }}"
        state: present
    - name: Download Maven packages
      get_url:  
        url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz 
        dest: /opt
    - name: Extract Maven packages
      unarchive: 
        src: /opt/apache-maven-3.9.6-bin.tar.gz
        dest: /opt
        remote_src: yes
# Add path to bash_profile (OPTIONAL)