---
- name: bootstrap server configuration
  hosts: maven
  become: true
  tasks:
    - name: download kubectl
      shell: curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    - name: Set executable permission on a kubectl file
      file:
        path: /home/ec2-user/kubectl
        mode: u+x,g+x,o+x
    - name: move kubectl file to /usr/local/bin 
      shell: mv /home/ec2-user/kubectl /usr/local/bin/kubectl
    # ######################################################################################
    - name: remove awcli if exist
      shell: yum remove awscli -y
    - name: download and rename awscli 
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
    - name: unzip awscli package 
      shell: unzip awscliv2.zip    
    - name: install awscli  
      shell: ./aws/install --update
    # ######################################################################################
